"""initial schema

Revision ID: 6476262218a0
Revises: 
Create Date: 2026-08-12 08:43:56.083733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6476262218a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'entity_type', name='uq_entity_name_type')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_table('research_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('new_source_count', sa.Integer(), nullable=True),
    sa.Column('reused_source_count', sa.Integer(), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=True),
    sa.Column('contradiction_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_jobs_created_at'), 'research_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_jobs_status'), 'research_jobs', ['status'], unique=False)
    op.create_table('knowledge_vectors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'object_id', name='uq_vector_object')
    )
    op.create_index(op.f('ix_knowledge_vectors_object_id'), 'knowledge_vectors', ['object_id'], unique=False)
    op.create_table('research_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('search_strategies', sa.JSON(), nullable=True),
    sa.Column('source_categories', sa.JSON(), nullable=True),
    sa.Column('evidence_requirements', sa.Text(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_job_id')
    )
    op.create_table('research_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_research_job_id'), 'research_runs', ['research_job_id'], unique=False)
    op.create_table('research_subquestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('focus_area', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_subquestions_research_job_id'), 'research_subquestions', ['research_job_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('normalized_url', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publication_date', sa.String(), nullable=True),
    sa.Column('retrieval_date', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('relevant_passages', sa.JSON(), nullable=True),
    sa.Column('citation_metadata', sa.JSON(), nullable=True),
    sa.Column('first_discovered_by_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['first_discovered_by_job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_content_hash'), 'sources', ['content_hash'], unique=False)
    op.create_index('ix_sources_hash', 'sources', ['content_hash'], unique=False)
    op.create_index(op.f('ix_sources_normalized_url'), 'sources', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('sub_question_id', sa.String(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('supporting_count', sa.Integer(), nullable=True),
    sa.Column('contradicting_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.Column('distinct_source_count', sa.Integer(), nullable=True),
    sa.Column('distinct_publisher_count', sa.Integer(), nullable=True),
    sa.Column('agreement_level', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_strength', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.ForeignKeyConstraint(['sub_question_id'], ['research_subquestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_research_job_id'), 'claims', ['research_job_id'], unique=False)
    op.create_index(op.f('ix_claims_sub_question_id'), 'claims', ['sub_question_id'], unique=False)
    op.create_table('conclusions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('sub_question_id', sa.String(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('supporting_claim_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.ForeignKeyConstraint(['sub_question_id'], ['research_subquestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conclusions_research_job_id'), 'conclusions', ['research_job_id'], unique=False)
    op.create_index(op.f('ix_conclusions_sub_question_id'), 'conclusions', ['sub_question_id'], unique=False)
    op.create_table('job_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('is_new_for_job', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'source_id', name='uq_job_source')
    )
    op.create_index(op.f('ix_job_sources_job_id'), 'job_sources', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_sources_source_id'), 'job_sources', ['source_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('conclusion_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('accessed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conclusion_id'], ['conclusions.id'], ),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_research_job_id'), 'citations', ['research_job_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('sub_question_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_strength', sa.String(), nullable=True),
    sa.Column('polarity', sa.Float(), nullable=True),
    sa.Column('date_hint', sa.String(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['sub_question_id'], ['research_subquestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_claim_id'), 'findings', ['claim_id'], unique=False)
    op.create_index(op.f('ix_findings_research_job_id'), 'findings', ['research_job_id'], unique=False)
    op.create_index(op.f('ix_findings_source_id'), 'findings', ['source_id'], unique=False)
    op.create_index(op.f('ix_findings_sub_question_id'), 'findings', ['sub_question_id'], unique=False)
    op.create_table('claim_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('stance', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'finding_id', name='uq_claim_finding')
    )
    op.create_index(op.f('ix_claim_findings_claim_id'), 'claim_findings', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_findings_finding_id'), 'claim_findings', ['finding_id'], unique=False)
    op.create_table('contradictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('claim_a_id', sa.String(), nullable=False),
    sa.Column('claim_b_id', sa.String(), nullable=True),
    sa.Column('finding_a_id', sa.String(), nullable=False),
    sa.Column('finding_b_id', sa.String(), nullable=False),
    sa.Column('source_a_id', sa.String(), nullable=False),
    sa.Column('source_b_id', sa.String(), nullable=False),
    sa.Column('contradiction_type', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('possible_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_a_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['claim_b_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['finding_a_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['finding_b_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_a_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['source_b_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contradictions_research_job_id'), 'contradictions', ['research_job_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_job_id', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['research_job_id'], ['research_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_research_job_id'), 'relationships', ['research_job_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_entity_id'), 'relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_entity_id'), 'relationships', ['target_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_target_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_research_job_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_contradictions_research_job_id'), table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_index(op.f('ix_claim_findings_finding_id'), table_name='claim_findings')
    op.drop_index(op.f('ix_claim_findings_claim_id'), table_name='claim_findings')
    op.drop_table('claim_findings')
    op.drop_index(op.f('ix_findings_sub_question_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_source_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_research_job_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_claim_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_citations_research_job_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_job_sources_source_id'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_job_id'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_conclusions_sub_question_id'), table_name='conclusions')
    op.drop_index(op.f('ix_conclusions_research_job_id'), table_name='conclusions')
    op.drop_table('conclusions')
    op.drop_index(op.f('ix_claims_sub_question_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_research_job_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_normalized_url'), table_name='sources')
    op.drop_index('ix_sources_hash', table_name='sources')
    op.drop_index(op.f('ix_sources_content_hash'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_research_subquestions_research_job_id'), table_name='research_subquestions')
    op.drop_table('research_subquestions')
    op.drop_index(op.f('ix_research_runs_research_job_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_table('research_plans')
    op.drop_index(op.f('ix_knowledge_vectors_object_id'), table_name='knowledge_vectors')
    op.drop_table('knowledge_vectors')
    op.drop_index(op.f('ix_research_jobs_status'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_created_at'), table_name='research_jobs')
    op.drop_table('research_jobs')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
